
import React, { useEffect } from 'react';
import { createPortal } from 'react-dom';
import { AssessmentQuestion } from '../../../types';
import { PrintStyles } from './PrintView/PrintStyles';
import { PrintHeader } from './PrintView/Header';
import { PrintQuestion } from './PrintView/Question';
import { SectionHeader } from './PrintView/SectionHeader';

export type PrintMode = 'BLANK' | 'WITH_ANSWERS' | 'WITH_ANSWERS_AND_FEEDBACK' | 'WITH_ANSWERS_MODEL' | 'MODEL_ANSWER_ONLY';

interface AssessmentPrintViewProps {
    participants: any[];
    questions: AssessmentQuestion[];
    ipekaLogoUrl: string;
    ibLogoUrl: string;
    className?: string;
    onAfterPrint: () => void;
    printMode: PrintMode;
}

export const AssessmentPrintView: React.FC<AssessmentPrintViewProps> = ({
    participants,
    questions,
    ipekaLogoUrl,
    ibLogoUrl,
    className,
    onAfterPrint,
    printMode
}) => {
    const totalPoints = questions.reduce((a, q) => a + q.points, 0);

    useEffect(() => {
        const originalTitle = document.title;
        document.title = `Generated by Classboards for ${className || 'Student'}`;

        const timer = setTimeout(() => {
            window.print();
        }, 300);

        const handleAfterPrint = () => {
            document.title = originalTitle;
            onAfterPrint();
        };

        window.addEventListener('afterprint', handleAfterPrint);

        return () => {
            document.title = originalTitle;
            clearTimeout(timer);
            window.removeEventListener('afterprint', handleAfterPrint);
        };
    }, [onAfterPrint, className]);

    const isBlankCopy = printMode === 'BLANK';
    const showAnswerKey = printMode === 'MODEL_ANSWER_ONLY';
    const includeStudentAnswers = (printMode === 'WITH_ANSWERS' || printMode === 'WITH_ANSWERS_AND_FEEDBACK' || printMode === 'WITH_ANSWERS_MODEL') && !isBlankCopy && !showAnswerKey;
    const includeFeedback = printMode === 'WITH_ANSWERS_AND_FEEDBACK' && !isBlankCopy && !showAnswerKey;
    const showModelAnswer = (printMode === 'WITH_ANSWERS_MODEL' || printMode === 'MODEL_ANSWER_ONLY') && !isBlankCopy;

    return createPortal(
        <div id="assessment-print-view">
            <style>{`
                @media print {
                    @page {
                        @bottom-right {
                            content: "Generated by Classboards for ${className || 'testing class'} | Page " counter(page) " of " counter(pages);
                            font-size: 9pt;
                            color: #666;
                        }
                    }
                }
            `}</style>
            <PrintStyles />

            {participants.map((participant, pIndex) => {
                const isRealStudent = !!participant.id && participant.id !== 'master-copy' && !showAnswerKey;

                return (
                    <div key={participant.id || pIndex} className="print-student-container">
                        <PrintHeader
                            ipekaLogoUrl={ipekaLogoUrl}
                            ibLogoUrl={ibLogoUrl}
                            isMasterKey={showAnswerKey}
                            isRealStudent={isRealStudent}
                            participantName={participant.name}
                            className={className}
                            score={participant.score}
                            totalPoints={totalPoints}
                            submissionDate={participant.submittedAt || null}
                        />

                        <div style={{ flex: 1 }}>
                            {questions.map((q, i) => {
                                if (q.type === 'section') {
                                    return <SectionHeader key={q.id} title={q.text} />;
                                }

                                const qNum = questions.slice(0, i + 1).filter(item => item.type !== 'section').length;
                                const answer = participant.data?.answers?.[q.id];
                                const gradeInfo = participant.data?.grading?.[q.id];

                                return (
                                    <PrintQuestion
                                        key={q.id}
                                        q={q}
                                        qNum={qNum}
                                        answer={includeStudentAnswers ? answer : undefined}
                                        gradeInfo={gradeInfo}
                                        isMasterKey={showAnswerKey}
                                        isRealStudent={isRealStudent}
                                        isBlankCopy={isBlankCopy}
                                        includeFeedback={includeFeedback}
                                        showModelAnswer={showModelAnswer}
                                    />
                                );
                            })}
                        </div>
                    </div>
                );
            })}
        </div>,
        document.body
    );
};
